#!/bin/bash


if [ $1 != "" ]; then
# Search all string based on date
awk '{sub("http://username:password@proxyIP:port","http://10.1.1.4:3128")}1' $1 > /etc/apt/apt.conf.d/01 && mv /etc/apt/apt.conf.d/01 $1
awk '{sub("https://username:password@proxyIP:port","https://10.1.1.4:3128")}1' $1 > /etc/apt/apt.conf.d/01 && mv /etc/apt/apt.conf.d/01 $1
fi