#!/bin/bash

# Check the command line argument value exists or not
if [ $1 != "" ]; then
# Search all string based on date
awk '{sub("#Acquire","Acquire")}1' $1 > /etc/apt/apt.conf.d/01 && mv /etc/apt/apt.conf.d/01 $1
fi